on:
  workflow_call:
    inputs:
      repo:
        description: 'repo'
        required: true
        default: ''
        type: string
      rate-limit:
        description: 'rate limit'
        required: false
        default: 150
        type: number
    secrets:
      GHPAT:
        required: true

jobs:
  metadata:
    runs-on: ubuntu-latest

    steps:
      - name: rate limit
        env:
          GHPAT: ${{ secrets.GHPAT }}
        run: |
          rl=$(curl -H "Authorization: token $GHPAT" -X GET https://api.github.com/rate_limit | jq '.rate.remaining')
          echo "Rate limit remaining: $rl"
          while [ $rl -lt ${{ inputs.rate-limit }} ]; do
            sleep 1h
            rl=$(curl -H "Authorization: token $GHPAT" -X GET https://api.github.com/rate_limit | jq '.rate.remaining')
            echo "Rate limit remaining: $rl"
          done

      - name: generate save directory name
        shell: bash
        id: vars
        run: |
          SREPO=$(echo -n ${{ inputs.repo }} | tr '/' .)
          echo "SREPO set to ${SREPO}"
          echo "SREPO=${SREPO}" >> $GITHUB_OUTPUT

      - name: checkout repo
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.repo }}
          token: ${{ secrets.GHPAT }}

      - name: run cloc
        run: |
          sudo apt-get update
          sudo apt-get install -y cloc
          cloc --json --report-file ${{ steps.vars.outputs.SREPO }}.cloc.json .

      - name: get metadata
        env:
          GH_TOKEN: ${{ secrets.GHPAT }}
        run: |
          gh api -H "Accept: application/vnd.github+json" /repos/${{ inputs.repo }} > ${{ steps.vars.outputs.SREPO }}.metadata.json

      - name: save results
        uses: actions/upload-artifact@v3
        with:
          retention-days: 10
          name: ${{ steps.vars.outputs.SREPO }}.metadata
          path: |
            ${{ steps.vars.outputs.SREPO }}.cloc.json
            ${{ steps.vars.outputs.SREPO }}.metadata.json
