name: Trigger monthly scan
permissions: read-all
on:
  schedule:
    - cron: '0 0 1 * *'
jobs:
  build:
    name: Trigger monthly scan
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GHPAT }}
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - run: gh workflow run query.yml -f search="archived:false language:c language:c++" -f minstars="400" -f increment="50"
