on:
  workflow_call:
    inputs:
      input:
        description: 'json array of inputs'
        required: true
        default: ''
        type: string
    secrets:
      GHPAT:
        required: true

jobs:
  split:
    uses: ./.github/workflows/work2matrix.yml
    with:
      input: ${{ inputs.input }}

  m1:
    needs: split
    if: needs.split.outputs.matrix1 != null
    secrets: inherit
    strategy:
      matrix: ${{fromJson(needs.split.outputs.matrix1)}}
      fail-fast: false # don't stop other jobs if one fails
    uses: ./.github/workflows/ossf-scorecard-steps.yml
    with:
      repo: ${{ matrix.repo }}

  m2:
    needs: split
    if: needs.split.outputs.matrix2 != null
    secrets: inherit
    strategy:
      matrix: ${{fromJson(needs.split.outputs.matrix2)}}
      fail-fast: false # don't stop other jobs if one fails
    uses: ./.github/workflows/ossf-scorecard-steps.yml
    with:
      repo: ${{ matrix.repo }}

  m3:
    needs: split
    if: needs.split.outputs.matrix3 != null
    secrets: inherit
    strategy:
      matrix: ${{fromJson(needs.split.outputs.matrix3)}}
      fail-fast: false # don't stop other jobs if one fails
    uses: ./.github/workflows/ossf-scorecard-steps.yml
    with:
      repo: ${{ matrix.repo }}

  m4:
    needs: split
    if: needs.split.outputs.matrix4 != null
    secrets: inherit
    strategy:
      matrix: ${{fromJson(needs.split.outputs.matrix4)}}
      fail-fast: false # don't stop other jobs if one fails
    uses: ./.github/workflows/ossf-scorecard-steps.yml
    with:
      repo: ${{ matrix.repo }}

  m5:
    needs: split
    if: needs.split.outputs.matrix5 != null
    secrets: inherit
    strategy:
      matrix: ${{fromJson(needs.split.outputs.matrix5)}}
      fail-fast: false # don't stop other jobs if one fails
    uses: ./.github/workflows/ossf-scorecard-steps.yml
    with:
      repo: ${{ matrix.repo }}

  m6:
    needs: split
    if: needs.split.outputs.matrix6 != null
    secrets: inherit
    strategy:
      matrix: ${{fromJson(needs.split.outputs.matrix6)}}
      fail-fast: false # don't stop other jobs if one fails
    uses: ./.github/workflows/ossf-scorecard-steps.yml
    with:
      repo: ${{ matrix.repo }}

  m7:
    needs: split
    if: needs.split.outputs.matrix7 != null
    secrets: inherit
    strategy:
      matrix: ${{fromJson(needs.split.outputs.matrix7)}}
      fail-fast: false # don't stop other jobs if one fails
    uses: ./.github/workflows/ossf-scorecard-steps.yml
    with:
      repo: ${{ matrix.repo }}

  m8:
    needs: split
    if: needs.split.outputs.matrix8 != null
    secrets: inherit
    strategy:
      matrix: ${{fromJson(needs.split.outputs.matrix8)}}
      fail-fast: false # don't stop other jobs if one fails
    uses: ./.github/workflows/ossf-scorecard-steps.yml
    with:
      repo: ${{ matrix.repo }}

  m9:
    needs: split
    if: needs.split.outputs.matrix9 != null
    secrets: inherit
    strategy:
      matrix: ${{fromJson(needs.split.outputs.matrix9)}}
      fail-fast: false # don't stop other jobs if one fails
    uses: ./.github/workflows/ossf-scorecard-steps.yml
    with:
      repo: ${{ matrix.repo }}

  m10:
    needs: split
    if: needs.split.outputs.matrix10 != null
    secrets: inherit
    strategy:
      matrix: ${{fromJson(needs.split.outputs.matrix10)}}
      fail-fast: false # don't stop other jobs if one fails
    uses: ./.github/workflows/ossf-scorecard-steps.yml
    with:
      repo: ${{ matrix.repo }}

  m11:
    needs: split
    if: needs.split.outputs.matrix11 != null
    secrets: inherit
    strategy:
      matrix: ${{fromJson(needs.split.outputs.matrix11)}}
      fail-fast: false # don't stop other jobs if one fails
    uses: ./.github/workflows/ossf-scorecard-steps.yml
    with:
      repo: ${{ matrix.repo }}

  m12:
    needs: split
    if: needs.split.outputs.matrix12 != null
    secrets: inherit
    strategy:
      matrix: ${{fromJson(needs.split.outputs.matrix12)}}
      fail-fast: false # don't stop other jobs if one fails
    uses: ./.github/workflows/ossf-scorecard-steps.yml
    with:
      repo: ${{ matrix.repo }}

  m13:
    needs: split
    if: needs.split.outputs.matrix13 != null
    secrets: inherit
    strategy:
      matrix: ${{fromJson(needs.split.outputs.matrix13)}}
      fail-fast: false # don't stop other jobs if one fails
    uses: ./.github/workflows/ossf-scorecard-steps.yml
    with:
      repo: ${{ matrix.repo }}
