on:
  workflow_call:
    inputs:
      repo:
        description: 'repo'
        required: true
        default: ''
        type: string
jobs:
  scan-build:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ github.token }}
      LLVM_VERSION: "15"
      TIMEOUT: "10m"

    defaults:
      run:
        shell: bash

    steps:
      - name: generate save directory name
        id: vars
        run: |
          srepo=$(echo ${{ inputs.repo }} | tr '/' .)

          echo "SREPO set to ${SREPO}"
          echo "SREPO=$srepo" >> $GITHUB_OUTPUT

      - name: checkout repo
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.repo }}
          path: repo

      - name: Get docker
        uses: actions/cache@v3
        id: get-docker
        with:
          path: scan-build.tar
          key: scan-build

      - name: Load image
        run: docker load -i scan-build.tar

      - name: scan-build
        run: docker run -v "$GITHUB_WORKSPACE":/work scan-build "${{ inputs.repo }}"

      - name: Remove docker
        run: rm scan-build.tar

      - name: convert to json
        if: ${{ always() }}
        env:
          SREPO: ${{ steps.vars.outputs.SREPO }}
        run: ./scan-build/convert2json.sh $SREPO

      - name: Adding scan summary to Github markdown
        if: ${{ always() }}
        env:
          SREPO: ${{ steps.vars.outputs.SREPO }}
        run: |
          cd $GITHUB_WORKSPACE
          bugs=$(jq '.bugs | length' $SREPO/result.json)
          functions=$(jq '.functions | length' $SREPO/result.json)
          if [ ${bugs} -gt 0 ]; then
            echo "### ${{ inputs.repo }}: ${bugs} bugs found" >> $GITHUB_STEP_SUMMARY
            echo "### Functions: $functions" >> $GITHUB_STEP_SUMMARY
            echo "#### Bug categories" >> $GITHUB_STEP_SUMMARY
            echo "| Category | Count |" >> $GITHUB_STEP_SUMMARY
            echo "| --- | --- |" >> $GITHUB_STEP_SUMMARY
            jq '.categories[] | "| \(.category) | \(.count) |"' $SREPO/result.json | tr -d '"' >> $GITHUB_STEP_SUMMARY
            echo "#### Bug types" >> $GITHUB_STEP_SUMMARY
            echo "| Type | Count |" >> $GITHUB_STEP_SUMMARY
            echo "| --- | --- |" >> $GITHUB_STEP_SUMMARY
            jq '.types[] | "| \(.type) | \(.count) |"' $SREPO/result.json | tr -d '"' >> $GITHUB_STEP_SUMMARY
          fi

      - name: compress result
        if: ${{ always() }}
        run: |
          USER=$(whoami)
          sudo chown -R $USER.$USER ${{ steps.vars.outputs.SREPO }}
          tar -czvf ${{ steps.vars.outputs.SREPO }}.${{ github.job }}.tar.gz --remove-files ${{ steps.vars.outputs.SREPO }}

      - name: save results
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          retention-days: 10
          name: ${{ steps.vars.outputs.SREPO }}.${{ github.job }}
          path: ${{ steps.vars.outputs.SREPO }}.${{ github.job }}.tar.gz
