name: Aggregate results and create summary
permissions: read-all
on:
  workflow_dispatch:
    inputs:
      run-ids:
        description: 'The workflow run-ids to look at'
        required: true
        type: string
      delay:
        description: 'Delay start to give previous workflow time to settle'
        required: false
        type: string
jobs:
  delay:
    runs-on: ubuntu-latest
    steps:
      - name: delay
        if: inputs.delay != ''
        run: sleep ${{ inputs.delay }}

  summary:
    needs: delay
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GHPAT }}
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GHPAT }}

      - name: free disk space
        run: ./query/free-disk-space.sh

      - id: vars
        run: |
          firstid=$(echo "${{ inputs.run-ids }}" | awk -F',' '{ print $1 }')
          echo "firstid=$firstid" >> $GITHUB_OUTPUT

      - name: Download artifacts with rate limit
        run: ./query/download-artifacts.sh "${{ inputs.run-ids }}"

      - name: Summarize results
        run: ./query/summary.sh "${{ steps.vars.outputs.firstid }}" "${{ inputs.run-ids }}"

      - name: Github step summary
        run: cat summary.md >> $GITHUB_STEP_SUMMARY

      - name: save results
        uses: actions/upload-artifact@v4
        with:
          retention-days: 90
          name: aggregate-results
          path: |
            score_vs_bugs.csv
            summary.md
            all-results.tar.gz

      - name: save scan results to gh pages
        run: |
          git fetch origin gh-pages --depth 1
          git checkout gh-pages

          git config --global user.name ${{ github.actor }}
          git config --global user.email '${{ github.actor }}@github.com'

          cd=$(date +"%Y.%m.%d")
          year=$(date +"%Y")
          d="$cd-${{ steps.vars.outputs.firstid }}"
          built=$(cat stats | awk -F',' '{ print $1 }')
          scored=$(cat stats | awk -F',' '{ print $2 }')
          bugs=$(cat stats | awk -F',' '{ print $3 }')
          cmplxf=$(cat stats | awk -F',' '{ print $4 }')

          mkdir -p scans/$d

          cp ${{ steps.vars.outputs.firstid }}/query-repositories/filtered-repos.json scans/$d
          cp all-results.tar.gz scans/$d
          cp summary.csv scans/$d

          echo "---" > scans/$d/index.md
          echo "layout: default" >> scans/$d/index.md
          echo "---" >> scans/$d/index.md
          echo "" >> scans/$d/index.md

          echo "## Scan date: $cd" >> scans/$d/index.md
          echo "[All results (tar.gz)](./all-results.tar.gz) [Repo list (JSON)](./filtered-repos.json) [Summary (CSV)](./summary.csv)" >> scans/$d/index.md

          echo "" >> scans/$d/index.md
          echo "***" >> scans/$d/index.md
          echo "" >> scans/$d/index.md

          cat ${{ steps.vars.outputs.firstid }}/query-repositories/query-summary.md >> scans/$d/index.md
          cat summary.md >> scans/$d/index.md

          echo "[back](../..)" >> scans/$d/index.md

          echo "$d,$cd,$year,$bugs,$built,$scored,$cmplxf" >> _data/scans.csv

          git add scans/$d
          git add _data/scans.csv

          git commit -m "Add scan results of date $d"
          git push
