on:
  workflow_call:
    inputs:
      input:
        description: 'array of json objects to split into work matrices'
        required: true
        default: '[]'
        type: string
    outputs:
      matrix1:
        description: "JSON array of max 256 inputs, base64 encoded"
        value: ${{ jobs.create-build-matrix.outputs.matrix1 }}
      matrix2:
        description: "JSON array of max 256 inputs, base64 encoded"
        value: ${{ jobs.create-build-matrix.outputs.matrix2 }}
      matrix3:
        description: "JSON array of max 256 inputs, base64 encoded"
        value: ${{ jobs.create-build-matrix.outputs.matrix3 }}
jobs:
  create-build-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix1: ${{ steps.matrix.outputs.matrix1 }}
      matrix2: ${{ steps.matrix.outputs.matrix2 }}
      matrix3: ${{ steps.matrix.outputs.matrix3 }}
      matrix4: ${{ steps.matrix.outputs.matrix4 }}
      matrix5: ${{ steps.matrix.outputs.matrix5 }}
      matrix6: ${{ steps.matrix.outputs.matrix6 }}
      matrix7: ${{ steps.matrix.outputs.matrix7 }}
      matrix8: ${{ steps.matrix.outputs.matrix8 }}
      matrix9: ${{ steps.matrix.outputs.matrix9 }}
      matrix10: ${{ steps.matrix.outputs.matrix10 }}
    steps:
      - name: save input
        run: echo -n ${{ inputs.input }} > input.json

      - name: create matrix
        id: matrix
        run: |

         COUNT=1
         MATRIXID=1

         JSON="{ include :["

         for row in $(jq -rc '.[]' input.json); do

              # Build matrices are limited to 256 items so we split the work
              if [ $(( $COUNT % 256 )) -eq 0 ]; then
                 # Remove last ","
                 JSON="${JSON%?}"
                 JSON+="]}"

                 echo "matrix${MATRIXID}=$JSON" >> $GITHUB_OUTPUT
                 echo "matrix${MATRIXID}=$JSON"

                 JSON="{ include: ["
                 (( MATRIXID++ ))
              fi

              JSON+="$row,"

              (( COUNT++ ))

              continue

         done

         # Remove last ","
         JSON="${JSON%?}"
         JSON+="]}"

         echo "matrix${MATRIXID}=$JSON" >> $GITHUB_OUTPUT
         echo "matrix${MATRIXID}=$JSON"
