on:
  workflow_call:
    inputs:
      input:
        description: 'array of json objects to split into work matrices'
        required: true
        default: '[]'
        type: string
    outputs:
      matrix1:
        description: "JSON array of max 256 inputs"
        value: ${{ jobs.create-build-matrix.outputs.matrix1 }}
      matrix2:
        description: "JSON array of max 256 inputs"
        value: ${{ jobs.create-build-matrix.outputs.matrix2 }}
      matrix3:
        description: "JSON array of max 256 inputs"
        value: ${{ jobs.create-build-matrix.outputs.matrix3 }}
      matrix4:
        description: "JSON array of max 256 inputs"
        value: ${{ jobs.create-build-matrix.outputs.matrix4 }}
      matrix5:
        description: "JSON array of max 256 inputs"
        value: ${{ jobs.create-build-matrix.outputs.matrix5 }}
      matrix6:
        description: "JSON array of max 256 inputs"
        value: ${{ jobs.create-build-matrix.outputs.matrix6 }}
      matrix7:
        description: "JSON array of max 256 inputs"
        value: ${{ jobs.create-build-matrix.outputs.matrix7 }}
      matrix8:
        description: "JSON array of max 256 inputs"
        value: ${{ jobs.create-build-matrix.outputs.matrix8 }}
      matrix9:
        description: "JSON array of max 256 inputs"
        value: ${{ jobs.create-build-matrix.outputs.matrix9 }}
      matrix10:
        description: "JSON array of max 256 inputs"
        value: ${{ jobs.create-build-matrix.outputs.matrix10 }}
      matrix11:
        description: "JSON array of max 256 inputs"
        value: ${{ jobs.create-build-matrix.outputs.matrix11 }}
      matrix12:
        description: "JSON array of max 256 inputs"
        value: ${{ jobs.create-build-matrix.outputs.matrix12 }}
      matrix13:
        description: "JSON array of max 256 inputs"
        value: ${{ jobs.create-build-matrix.outputs.matrix13 }}
      matrix14:
        description: "JSON array of max 256 inputs"
        value: ${{ jobs.create-build-matrix.outputs.matrix14 }}
      matrix15:
        description: "JSON array of max 256 inputs"
        value: ${{ jobs.create-build-matrix.outputs.matrix15 }}
      matrix16:
        description: "JSON array of max 256 inputs"
        value: ${{ jobs.create-build-matrix.outputs.matrix16 }}
      matrix17:
        description: "JSON array of max 256 inputs"
        value: ${{ jobs.create-build-matrix.outputs.matrix17 }}
      matrix18:
        description: "JSON array of max 256 inputs"
        value: ${{ jobs.create-build-matrix.outputs.matrix18 }}
      matrix19:
        description: "JSON array of max 256 inputs"
        value: ${{ jobs.create-build-matrix.outputs.matrix19 }}
      matrix20:
        description: "JSON array of max 256 inputs"
        value: ${{ jobs.create-build-matrix.outputs.matrix20 }}

jobs:
  create-build-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix1: ${{ steps.matrix.outputs.matrix1 }}
      matrix2: ${{ steps.matrix.outputs.matrix2 }}
      matrix3: ${{ steps.matrix.outputs.matrix3 }}
      matrix4: ${{ steps.matrix.outputs.matrix4 }}
      matrix5: ${{ steps.matrix.outputs.matrix5 }}
      matrix6: ${{ steps.matrix.outputs.matrix6 }}
      matrix7: ${{ steps.matrix.outputs.matrix7 }}
      matrix8: ${{ steps.matrix.outputs.matrix8 }}
      matrix9: ${{ steps.matrix.outputs.matrix9 }}
      matrix10: ${{ steps.matrix.outputs.matrix10 }}
      matrix11: ${{ steps.matrix.outputs.matrix11 }}
      matrix12: ${{ steps.matrix.outputs.matrix12 }}
      matrix13: ${{ steps.matrix.outputs.matrix13 }}
      matrix14: ${{ steps.matrix.outputs.matrix14 }}
      matrix15: ${{ steps.matrix.outputs.matrix15 }}
      matrix16: ${{ steps.matrix.outputs.matrix16 }}
      matrix17: ${{ steps.matrix.outputs.matrix17 }}
      matrix18: ${{ steps.matrix.outputs.matrix18 }}
      matrix19: ${{ steps.matrix.outputs.matrix19 }}
      matrix20: ${{ steps.matrix.outputs.matrix20 }}
    steps:
      - name: save input
        run: echo -n '${{ inputs.input }}' > input.json

      - name: create matrix
        id: matrix
        run: |

         COUNT=1
         MATRIXID=1

         JSON="{ include :["

         for row in $(jq -rc '.[]' input.json); do

              # Build matrices are limited to 256 items so we split the work
              if [ $(( $COUNT % 256 )) -eq 0 ]; then
                 # Remove last ","
                 JSON="${JSON%?}"
                 JSON+="]}"

                 echo "matrix${MATRIXID}=$JSON" >> $GITHUB_OUTPUT
                 echo "$JSON" > matrix${MATRIXID}.json

                 JSON="{ include: ["
                 (( MATRIXID++ ))
              fi

              JSON+="$row,"

              (( COUNT++ ))

         done

         # Remove last ","
         JSON="${JSON%?}"
         JSON+="]}"

         echo "matrix${MATRIXID}=$JSON" >> $GITHUB_OUTPUT
         echo "$JSON" > matrix${MATRIXID}.json

      - name: save results
        uses: actions/upload-artifact@v3
        with:
          retention-days: 10
          name: matrix-${{ github.run_id }}
          path: matrix*.json
